# Generated by Django 5.1.3 on 2025-06-04 17:16

import personal_assistant.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=personal_assistant.storages_backends.MediaStorage(), upload_to='avatars/'),
        ),
    ]
