# Generated by Django 5.1.3 on 2025-06-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/%u/')),
                ('original_extension', models.CharField(blank=True, max_length=10, null=True)),
                ('public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], max_length=20)),
                ('resource_type', models.CharField(blank=True, max_length=50, null=True)),
                ('preview', models.FileField(blank=True, null=True, upload_to='previews/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
